title: bear-with-data
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

pages:
- uber_fares_analysis.md
- laptop_price_prediction.md
- daily-temperature-forecast.md
- kuala-lumpur-rain-prediction.md
