title: bear-with-data
remote_theme: jylim21/jekyll-text-theme
plugins:
- jekyll-remote-theme

pages:
- uber-fares-analysis/uber_fares_analysis.md
- laptop_price_prediction.md
- daily-temperature-forecast.md
- kuala-lumpur-rain-prediction.md
