title: bear-with-data
remote_theme: jylim21/jylim21.github.io
plugins:
- jekyll-remote-theme

highlight_theme: tomorrow-night

pages:
- uber-fares-analysis/uber_fares_analysis.md
- laptop_price_prediction.md
- daily-temperature-forecast.md
- kuala-lumpur-rain-prediction.md
